


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.tg.view;

import fatec.tg.controle.ClockLabelData;
import fatec.tg.controle.GerenteJanelas;
import fatec.tg.controle.Sessao;
import fatec.tg.model.Usuario;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.net.URL;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.plaf.ColorUIResource;

/**
 *
 * @author Geovana Cânovas
 */
public class GuiMenu extends javax.swing.JFrame {
    public GuiExcluirTitulo passarUsuario;
    GerenteJanelas gerenteDeJanelas;
    /**
     * Creates new form GuiMenu
     */
    public GuiMenu() {
        initComponents();
        this.gerenteDeJanelas=new GerenteJanelas(painelMenu);
        URL url = this.getClass().getResource("/fatec/resources/logo2.png");  
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);  
        this.setIconImage(iconeTitulo);
        
        
    }
    private GuiConsultarFornecedor guiConsultarFornecedor;
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        try {
            //img = ImageIO.read(new URL("http://www.portoalegre.travel/upload/b/31/310717_simple-abstract-wallpaper.jpg"));
            img = javax.imageio.ImageIO.read(new java.net.URL(getClass().getResource("/fatec/resources/fundo3.jpg"), "fundo3.jpg"));
            //ImageIcon img = new ImageIcon("\\fundo.jpg");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        painelMenu = new javax.swing.JDesktopPane(){
            @Override
            protected void paintComponent(Graphics grphcs) {
                super.paintComponent(grphcs);
                grphcs.drawImage(img, 0, 0, null);
            }

            @Override
            public Dimension getPreferredSize() {
                return new Dimension(img.getWidth(), img.getHeight());
            }
        };
        Imagem = new javax.swing.JLabel();
        jToolBarRodape = new javax.swing.JToolBar();
        jPanel1 = new javax.swing.JPanel();
        jLabelNome = new javax.swing.JLabel();
        jLabelData = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelHora = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuContasAPagar = new javax.swing.JMenuItem();
        jMenuItemContasPagas = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuFornecedor = new javax.swing.JMenuItem();
        jMenuTipoPag = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemRemessa = new javax.swing.JMenuItem();
        jMenuItemRetorno = new javax.swing.JMenuItem();
        jMenuItemConciliacao = new javax.swing.JMenuItem();
        jMenuItemSumulacao = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Eleven Idiomas");
        setBackground(new java.awt.Color(255, 255, 255));
        setExtendedState(6);
        setFocusCycleRoot(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        painelMenu.setBackground(new java.awt.Color(153, 102, 255));
        painelMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        painelMenu.setPreferredSize(new java.awt.Dimension(436, 720));

        Imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/resources/logomenu.png"))); // NOI18N
        Imagem.setPreferredSize(new java.awt.Dimension(500, 500));

        painelMenu.setLayer(Imagem, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout painelMenuLayout = new javax.swing.GroupLayout(painelMenu);
        painelMenu.setLayout(painelMenuLayout);
        painelMenuLayout.setHorizontalGroup(
            painelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelMenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Imagem, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        painelMenuLayout.setVerticalGroup(
            painelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelMenuLayout.createSequentialGroup()
                .addGap(0, 251, Short.MAX_VALUE)
                .addComponent(Imagem, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jToolBarRodape.setBackground(new java.awt.Color(255, 255, 255));
        jToolBarRodape.setBorder(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabelNome.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNome.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelNome.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabelData = new fatec.tg.controle.ClockLabelData();
        jLabelData.setBackground(new java.awt.Color(255, 255, 255));
        jLabelData.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelData.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Usuario:  ");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Data: ");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Hora: ");

        jLabelHora = new fatec.tg.controle.ClockLabelHoras();
        jLabelHora.setBackground(new java.awt.Color(255, 255, 255));
        jLabelHora.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelHora.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelHora, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabelHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/tg/icon/user.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 839, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelData, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabelNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jToolBarRodape.add(jPanel1);

        jMenuBar1.setBackground(java.awt.Color.white);
        jMenuBar1.setBorderPainted(false);
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(171, 30));

        jMenu2.setBackground(new java.awt.Color(255, 255, 255));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/tg/icon/graph.png"))); // NOI18N
        jMenu2.setText("Finanças");

        jMenuContasAPagar.setBackground(new java.awt.Color(255, 255, 255));
        jMenuContasAPagar.setText("Contas a Pagar");
        jMenuContasAPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuContasAPagarActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuContasAPagar);

        jMenuItemContasPagas.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItemContasPagas.setText("Contas Pagas");
        jMenuItemContasPagas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemContasPagasActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemContasPagas);
        jMenu2.add(jSeparator1);

        jMenuFornecedor.setBackground(new java.awt.Color(255, 255, 255));
        jMenuFornecedor.setText("Fornecedor");
        jMenuFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFornecedorActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuFornecedor);

        jMenuTipoPag.setBackground(new java.awt.Color(255, 255, 255));
        jMenuTipoPag.setText("Tipo de Pagamento");
        jMenuTipoPag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuTipoPagActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuTipoPag);
        jMenu2.add(jSeparator2);

        jMenuItemRemessa.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItemRemessa.setText("Arquivo Remessa");
        jMenuItemRemessa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRemessaActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemRemessa);

        jMenuItemRetorno.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItemRetorno.setText("Arquivo Retorno");
        jMenuItemRetorno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRetornoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemRetorno);

        jMenuItemConciliacao.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItemConciliacao.setText("Conciliação Bancária");
        jMenuItemConciliacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConciliacaoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemConciliacao);

        jMenuItemSumulacao.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItemSumulacao.setText("Simulação de Contas");
        jMenuItemSumulacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSumulacaoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemSumulacao);

        jMenuBar1.add(jMenu2);

        jMenuSair.setBackground(new java.awt.Color(255, 255, 255));
        jMenuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/tg/icon/exit.png"))); // NOI18N
        jMenuSair.setText("Sair");
        jMenuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSairMouseClicked(evt);
            }
        });
        jMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSairActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBarRodape, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(painelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 1330, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBarRodape, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemContasPagasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemContasPagasActionPerformed

          gerenteDeJanelas.abrirJanelas(GuiContasPagas.getInstancia());
          gerenteDeJanelas.setPosicao(GuiContasPagas.getInstancia());
          
    }//GEN-LAST:event_jMenuItemContasPagasActionPerformed

    private void jMenuFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFornecedorActionPerformed
       
           gerenteDeJanelas.abrirJanelas(GuiConsultarFornecedor.getInstancia());
            gerenteDeJanelas.setPosicao(GuiConsultarFornecedor.getInstancia());
    }//GEN-LAST:event_jMenuFornecedorActionPerformed

    private void jMenuItemRemessaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRemessaActionPerformed
           gerenteDeJanelas.abrirJanelas(GuiArquivoRemessas.getInstancia());
            gerenteDeJanelas.setPosicao(GuiArquivoRemessas.getInstancia());
    }//GEN-LAST:event_jMenuItemRemessaActionPerformed

    private void jMenuTipoPagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuTipoPagActionPerformed

            gerenteDeJanelas.abrirJanelas(GuiConsultarTipoPag.getInstancia());
            gerenteDeJanelas.setPosicao(GuiConsultarTipoPag.getInstancia());
    }//GEN-LAST:event_jMenuTipoPagActionPerformed

    private void jMenuContasAPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuContasAPagarActionPerformed
            gerenteDeJanelas.abrirJanelas(GuiContasAPagar.getInstancia());
            gerenteDeJanelas.setPosicao(GuiContasAPagar.getInstancia());
       
    }//GEN-LAST:event_jMenuContasAPagarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        DateTimeFormatter d = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        DateTimeFormatter h = DateTimeFormatter.ofPattern("HH:mm:ss");
        //Sessao sessao = Sessao.getInstance();
                
        //usuario=new Usuario(123);
        //usuario.setUsuario("Devair JR");
        //sessao.setUsuario(usuario);
        usuario=Sessao.getInstance().getUsuario();
        LocalDateTime timePoint = LocalDateTime.now();
        jToolBarRodape.setVisible(true);
        jLabelNome.setText(usuario.getUsuario());
        jLabelHora.setText(timePoint.format(h));
        jLabelData.setText(timePoint.format(d));
    }//GEN-LAST:event_formWindowOpened

    private void jMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSairActionPerformed

    }//GEN-LAST:event_jMenuSairActionPerformed

    private void jMenuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSairMouseClicked
        // TODO add your handling code here:
         dispose();
    }//GEN-LAST:event_jMenuSairMouseClicked

    private void jMenuItemSumulacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSumulacaoActionPerformed

          gerenteDeJanelas.abrirJanelas(GuiSimulacaoContasAPagar.getInstancia());
          gerenteDeJanelas.setPosicao(GuiSimulacaoContasAPagar.getInstancia());
    }//GEN-LAST:event_jMenuItemSumulacaoActionPerformed

    private void jMenuItemRetornoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRetornoActionPerformed
       gerenteDeJanelas.abrirJanelas(GuiArquivoRetorno.getInstancia());
       gerenteDeJanelas.setPosicao(GuiArquivoRetorno.getInstancia());
    }//GEN-LAST:event_jMenuItemRetornoActionPerformed

    private void jMenuItemConciliacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConciliacaoActionPerformed
         gerenteDeJanelas.abrirJanelas(GuiConciliacaoBancaria.getInstancia());
         gerenteDeJanelas.setPosicao(GuiConciliacaoBancaria.getInstancia());
    }//GEN-LAST:event_jMenuItemConciliacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiMenu().setVisible(true);
               
                //192,230,217
                //UIManager.put ("nimbusBase", new ColorUIResource(102,102,102));
                //UIManager.put ("nimbusSelection", new ColorUIResource(0,0,102)); 
                
                UIManager.put ("MenuItem[Enabled].textBackground", new ColorUIResource(255,255,255));
               // UIManager.put ("nimbusSelectionBackground", new ColorUIResource(102,102,102));       
                UIManager.put ("nimbusBlueGrey", new ColorUIResource(255,255,255));
                UIManager.put ("control", new ColorUIResource(255,255,255));
                UIManager.put ("Button.background", new ColorUIResource(255,255,255));
                UIManager.put ("ComboBox.renderer", new ColorUIResource(255,0,0));
                	
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Imagem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuContasAPagar;
    private javax.swing.JMenuItem jMenuFornecedor;
    private javax.swing.JMenuItem jMenuItemConciliacao;
    private javax.swing.JMenuItem jMenuItemContasPagas;
    private javax.swing.JMenuItem jMenuItemRemessa;
    private javax.swing.JMenuItem jMenuItemRetorno;
    private javax.swing.JMenuItem jMenuItemSumulacao;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JMenuItem jMenuTipoPag;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JToolBar jToolBarRodape;
    public static javax.swing.JDesktopPane painelMenu;
    // End of variables declaration//GEN-END:variables
    private BufferedImage img;
    public Usuario usuario=null;
}
