/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.tg.view;

import fatec.tg.controle.Admin;
import fatec.tg.controle.Conexao;
import fatec.tg.controle.DaoAgencia;
import fatec.tg.controle.DaoArquivoRemessa;
import fatec.tg.controle.DaoBanco;
import fatec.tg.controle.DaoContaBancaria;
import fatec.tg.controle.DaoFornecPF;
import fatec.tg.controle.DaoFornecPJ;
import fatec.tg.controle.DaoFornecedor;
import fatec.tg.controle.DaoRecorrente;
import fatec.tg.controle.DaoRemessaTitulo;
import fatec.tg.controle.DaoSubconta;
import fatec.tg.controle.DaoTitulo;
import fatec.tg.controle.DaoTituloParcela;
import fatec.tg.controle.DaoTpPagamento;
import fatec.tg.controle.GerenteJanelas;
import fatec.tg.model.Agencia;
import fatec.tg.model.ArquivoRemessa;
import fatec.tg.model.Banco;
import fatec.tg.model.ContaBancaria;
import fatec.tg.model.FornecFisica;
import fatec.tg.model.FornecJuridica;
import fatec.tg.model.Fornecedor;
import fatec.tg.model.RemessaTitulo;
import fatec.tg.model.TipoPagamento;
import fatec.tg.model.Titulo;
import fatec.tg.model.TituloParcela;
import static fatec.tg.view.GuiMenu.painelMenu;
import java.awt.Color;
import java.awt.Dimension;
import java.text.ParseException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javafx.scene.paint.Color.color;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.plaf.ColorUIResource;

/**
 *
 * @author Bia Delmont
 */
public class GuiPagarTitulo extends javax.swing.JInternalFrame {
    private GuiContasAPagar guiContasAPagar;
    public GerenteJanelas gerenteJanelas;
    /**
     * Creates new form GuiPagarTitulos
     */
    public GuiPagarTitulo() {
        initComponents();
        this.gerenteJanelas=new GerenteJanelas(painelMenu);
    }
    public void setPosicao(){
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);   
    }
    public void RecebeParcela(int nl,int np){
        numLanc=nl;
        numParc=np;
    }
    
    public  String buscaFornec(int cod){
        fornecFisica=daoFornecPF.consultar(cod);
        if(fornecFisica==null){
            fornecJuridica=daoFornecPJ.consultar(cod);
            return fornecJuridica.getNomeFan();
        }
        else{
             return fornecFisica.getNome();
           
        }
        
     }
     public String buscaNomeBanco(int cod){
      banco=daoBanco.consultar(cod);
      return(banco.getNome());
  }
       public int buscaCodBanco(String nome){
      banco=daoBanco.consultarNome(nome);
      return(banco.getCodBanco());
  }
     public void bancario(){
        jPanelBancario.setEnabled(true);
        cbxBanco.setEnabled(true);
        cbxAgencia.setEnabled(true);
        cbxContaBancaria.setEnabled(true);
        jtxtSaldo.setEnabled(true);
       
        daoAgencia=new DaoAgencia(conexao.conectar());
        daoContaBancaria=new DaoContaBancaria(conexao.conectar());
        ArrayList<Banco> bancos = daoBanco.listarBancos();
        for(int x=0;x<bancos.size();x++){
            cbxBanco.addItem(bancos.get(x).getNome());
        }
         
     }
     public void completaTitulo(){
            tituloParcela.setTipoPagamento(daotpPagamento.consultarDescricao((String) cbxTipoPagamento.getSelectedItem()));
            tituloParcela.setValorPago(Double.parseDouble(jtxtValPagar.getText()));
            tituloParcela.setDataPag(jtxtDtPagamento.getText());
            
            
     }
    public void AtualizaTitulos(){
    
    guiContasAPagar.btnExibir.setSelected(true);
        
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPagar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtCodBarras = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtFornecedor = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtHistorico = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jtxtDtVencimento = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNumLancamento = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jtxtMulta = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtTitularidade = new javax.swing.JTextField();
        txtNumParcelas = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jtxtDtPagamento = new javax.swing.JFormattedTextField();
        jtxtJuros = new javax.swing.JFormattedTextField();
        jtxtValor = new javax.swing.JFormattedTextField();
        jtxtValPagar = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        cbxTipoPagamento = new javax.swing.JComboBox<>();
        jPanelBancario = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cbxAgencia = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jtxtSaldo = new javax.swing.JFormattedTextField();
        cbxBanco = new javax.swing.JComboBox<>();
        cbxContaBancaria = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jPanelCheque = new javax.swing.JPanel();
        txtNumCheque = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jtxtDtPredatado = new javax.swing.JFormattedTextField();
        jLabel24 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setTitle("Pagar Titulo");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        btnPagar.setBackground(new java.awt.Color(255, 255, 255));
        btnPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/tg/icon/icons8-dinheiro-32.png"))); // NOI18N
        btnPagar.setText("Pagar");
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/tg/icon/icons8-cancelar-30.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtCodBarras.setEditable(false);
        txtCodBarras.setBackground(new java.awt.Color(255, 255, 255));
        txtCodBarras.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setText("Nosso Numero");

        txtFornecedor.setEditable(false);
        txtFornecedor.setBackground(new java.awt.Color(255, 255, 255));
        txtFornecedor.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel18.setText("Histórico");

        jLabel10.setText("Fornecedor");

        txtHistorico.setEditable(false);
        txtHistorico.setBackground(new java.awt.Color(255, 255, 255));
        txtHistorico.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHistoricoActionPerformed(evt);
            }
        });

        jLabel6.setText("Vencimento");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Pagar título");

        jtxtDtVencimento.setEditable(false);
        jtxtDtVencimento.setBackground(new java.awt.Color(255, 255, 255));
        jtxtDtVencimento.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        try {
            jtxtDtVencimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel2.setText("Nº Lançamento");

        txtNumLancamento.setEditable(false);
        txtNumLancamento.setBackground(new java.awt.Color(255, 255, 255));
        txtNumLancamento.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtNumLancamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumLancamentoActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder()));

        jLabel7.setText("Valor ");

        jLabel8.setText("Nº da Parcela");

        jLabel14.setText("Multa de atraso");

        jtxtMulta.setEditable(false);
        jtxtMulta.setBackground(new java.awt.Color(255, 255, 255));
        jtxtMulta.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jtxtMulta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        jLabel13.setText("Juros");

        jLabel19.setText("Titularidade");

        txtTitularidade.setEditable(false);
        txtTitularidade.setBackground(new java.awt.Color(255, 255, 255));
        txtTitularidade.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtTitularidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTitularidadeActionPerformed(evt);
            }
        });

        txtNumParcelas.setEditable(false);
        txtNumParcelas.setBackground(new java.awt.Color(255, 255, 255));
        txtNumParcelas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtNumParcelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumParcelasActionPerformed(evt);
            }
        });

        jLabel20.setText("Valor a Pagar");

        jLabel21.setText("Data Pagamento");

        jtxtDtPagamento.setEditable(false);
        jtxtDtPagamento.setBackground(new java.awt.Color(255, 255, 255));
        jtxtDtPagamento.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        try {
            jtxtDtPagamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtxtDtPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDtPagamentoActionPerformed(evt);
            }
        });

        jtxtJuros.setEditable(false);
        jtxtJuros.setBackground(new java.awt.Color(255, 255, 255));
        jtxtJuros.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jtxtJuros.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        jtxtValor.setEditable(false);
        jtxtValor.setBackground(new java.awt.Color(255, 255, 255));
        jtxtValor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jtxtValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        jtxtValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtValorActionPerformed(evt);
            }
        });

        jtxtValPagar.setEditable(false);
        jtxtValPagar.setBackground(new java.awt.Color(255, 255, 255));
        jtxtValPagar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jtxtValPagar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtDtPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtJuros, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNumParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtTitularidade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                        .addComponent(jtxtMulta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                        .addComponent(jtxtValPagar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                        .addComponent(jtxtValor, javax.swing.GroupLayout.Alignment.TRAILING)))))))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jtxtJuros, jtxtMulta, jtxtValPagar, txtTitularidade});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtNumParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtxtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jtxtMulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jtxtJuros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtTitularidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jtxtValPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jtxtDtPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jtxtDtPagamento, jtxtJuros, jtxtMulta, jtxtValPagar, jtxtValor, txtNumParcelas, txtTitularidade});

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Forma de Pagamento"));

        cbxTipoPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        cbxTipoPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoPagamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbxTipoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbxTipoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanelBancario.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder()));
        jPanelBancario.setEnabled(false);

        jLabel16.setText("Banco:");

        jLabel17.setText("Nº da conta:");

        cbxAgencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        cbxAgencia.setEnabled(false);
        cbxAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxAgenciaActionPerformed(evt);
            }
        });

        jLabel22.setText("Agência:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Saldo:");

        jtxtSaldo.setEditable(false);
        jtxtSaldo.setBackground(new java.awt.Color(255, 255, 255));
        jtxtSaldo.setEnabled(false);
        jtxtSaldo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        cbxBanco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        cbxBanco.setEnabled(false);
        cbxBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxBancoActionPerformed(evt);
            }
        });

        cbxContaBancaria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        cbxContaBancaria.setEnabled(false);
        cbxContaBancaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxContaBancariaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBancarioLayout = new javax.swing.GroupLayout(jPanelBancario);
        jPanelBancario.setLayout(jPanelBancarioLayout);
        jPanelBancarioLayout.setHorizontalGroup(
            jPanelBancarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBancarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBancarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBancarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBancarioLayout.createSequentialGroup()
                        .addGroup(jPanelBancarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelBancarioLayout.createSequentialGroup()
                                .addComponent(cbxBanco, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(19, 19, 19))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBancarioLayout.createSequentialGroup()
                                .addComponent(cbxAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addComponent(jLabel15)
                        .addGap(21, 21, 21)
                        .addComponent(jtxtSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                    .addComponent(cbxContaBancaria, 0, 115, Short.MAX_VALUE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jPanelBancarioLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbxAgencia, cbxBanco, cbxContaBancaria});

        jPanelBancarioLayout.setVerticalGroup(
            jPanelBancarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBancarioLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanelBancarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBancarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jtxtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanelBancarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxContaBancaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addContainerGap())
        );

        jPanelBancarioLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbxAgencia, cbxBanco, cbxContaBancaria});

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/resources/logopp.png"))); // NOI18N

        jPanelCheque.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Cheque"));
        jPanelCheque.setEnabled(false);

        txtNumCheque.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtNumCheque.setEnabled(false);

        jLabel23.setText("Pré Datado");

        jtxtDtPredatado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        try {
            jtxtDtPredatado.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtxtDtPredatado.setEnabled(false);

        jLabel24.setText("Numero cheque:");

        javax.swing.GroupLayout jPanelChequeLayout = new javax.swing.GroupLayout(jPanelCheque);
        jPanelCheque.setLayout(jPanelChequeLayout);
        jPanelChequeLayout.setHorizontalGroup(
            jPanelChequeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChequeLayout.createSequentialGroup()
                .addGroup(jPanelChequeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(jtxtDtPredatado, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelChequeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(txtNumCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelChequeLayout.setVerticalGroup(
            jPanelChequeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChequeLayout.createSequentialGroup()
                .addGroup(jPanelChequeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelChequeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtDtPredatado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelBancario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelCheque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNumLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(txtCodBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtxtDtVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel18)
                                .addComponent(txtHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(38, 38, 38)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(txtFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNumLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtDtVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanelBancario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHistoricoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHistoricoActionPerformed

    private void txtNumLancamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumLancamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumLancamentoActionPerformed

    private void txtTitularidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTitularidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTitularidadeActionPerformed

    private void txtNumParcelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumParcelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumParcelasActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        conexao = new Conexao();
        daoFornecedor = new DaoFornecedor(conexao.conectar());
        daoFornecPF = new DaoFornecPF(conexao.conectar());
        daoFornecPJ = new DaoFornecPJ(conexao.conectar());
        daoTitulo =new DaoTitulo(conexao.conectar());
        daoTituloParcela=new DaoTituloParcela(conexao.conectar());
        daoBanco=new DaoBanco(conexao.conectar());
        daotpPagamento=new DaoTpPagamento(conexao.conectar());
        daoArquivoRemessa=new DaoArquivoRemessa(conexao.conectar());
        daoRemessaTitulo= new DaoRemessaTitulo((conexao.conectar()));
        
        Date hoje =new Date();
        ArrayList<TipoPagamento> tiposPg = daotpPagamento.listarTpPagamento();
        for(int x=0;x<tiposPg.size();x++){
            cbxTipoPagamento.addItem(tiposPg.get(x).getDescricao());
        }
        titulo= daoTitulo.consultar(numLanc);
        tituloParcela= daoTituloParcela.consultar(numLanc, numParc);
        Date dtvenc = null;
        double multa=0;
        double juros=0;
        try {
            dtvenc = (Date)Admin.formataData(tituloParcela.getDataVenc());
        } catch (ParseException ex) {
            Logger.getLogger(GuiPagarTitulo.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        Calendar a = Calendar.getInstance();
        a.setTime(hoje);//data maior
        Calendar b = Calendar.getInstance();
        b.setTime(dtvenc);// data menor
        if(hoje.after(dtvenc)){
          a.add(Calendar.DATE, - b.get(Calendar.DAY_OF_MONTH));
          jtxtJuros.setText(String.valueOf(a.get(Calendar.DAY_OF_MONTH)*titulo.getJuros()));
          multa=titulo.getMulta();
          juros=a.get(Calendar.DAY_OF_MONTH)*titulo.getJuros();
        }else{
            multa=0;
            jtxtJuros.setText(String.valueOf(0));
        }
         txtNumLancamento.setText(String.valueOf(titulo.getNumLancamento()));
         txtCodBarras.setText(tituloParcela.getNossoNum());
         txtNumParcelas.setText(String.valueOf(tituloParcela.getNumParcela()));
         jtxtDtVencimento.setText(tituloParcela.getDataVenc());
         txtHistorico.setText(titulo.getHistorico());
         txtTitularidade.setText(title);
         txtFornecedor.setText(buscaFornec(titulo.getFornecedor().getCodFornec()));
         txtTitularidade.setText(buscaNomeBanco(titulo.getBanco().getCodBanco()));
         jtxtValor.setText(String.valueOf(tituloParcela.getValorParcela()));
         jtxtMulta.setText(String.valueOf(multa));
         jtxtValPagar.setText(String.valueOf(tituloParcela.getValorParcela()+multa+juros));
         DateTimeFormatter d = DateTimeFormatter.ofPattern("dd/MM/yyyy");
         LocalDateTime timePoint = LocalDateTime.now();
         jtxtDtPagamento.setText(timePoint.format(d));
       
         
    }//GEN-LAST:event_formInternalFrameOpened

    private void cbxTipoPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoPagamentoActionPerformed
        // TODO add your handling code here:
        if(cbxTipoPagamento.getSelectedItem().equals("Transferencia Bancaria")){
            bancario();
            jtxtDtPredatado.setText("");
            txtNumCheque.setText("");
            jPanelCheque.setEnabled(false);
            jtxtDtPredatado.setEnabled(false);
            txtNumCheque.setEnabled(false);
            
        }
        else if(cbxTipoPagamento.getSelectedItem().equals("Remessa")){
            if(tituloParcela.getNossoNum()==null){
                 JOptionPane.showMessageDialog(this, "Titulo invalido. Nosso número ausente no cadastro");
                 cbxTipoPagamento.setSelectedIndex(0);
            }else{
                bancario();
                jtxtDtPredatado.setText("");
                txtNumCheque.setText("");
                jPanelCheque.setEnabled(false);
                jtxtDtPredatado.setEnabled(false);
                txtNumCheque.setEnabled(false);
            }
             
        }
        else if(cbxTipoPagamento.getSelectedItem().equals("Cheque")){
            jPanelCheque.setEnabled(true);
            jtxtDtPredatado.setEnabled(true);
            txtNumCheque.setEnabled(true);
            jPanelBancario.setEnabled(false);
            cbxAgencia.setSelectedIndex(0);
            cbxBanco.setSelectedIndex(0);
            cbxContaBancaria.setSelectedIndex(0);
            cbxAgencia.setEnabled(false);
            cbxBanco.setEnabled(false);
            cbxContaBancaria.setEnabled(false);
            
            
        }
         else if(cbxTipoPagamento.getSelectedItem().equals("Dinheiro")){
             System.out.println("passei dinheiro");
            jPanelCheque.setEnabled(false);
            jtxtDtPredatado.setEnabled(false);
            txtNumCheque.setEnabled(false);
            
            jPanelBancario.setEnabled(false);
            cbxAgencia.setEnabled(false);
            cbxBanco.setEnabled(false);
            cbxBanco.setSelectedIndex(0);
            cbxContaBancaria.setEnabled(false);
            cbxAgencia.setSelectedIndex(0);
           
            cbxContaBancaria.setSelectedIndex(0);
            
        }
            
        
    }//GEN-LAST:event_cbxTipoPagamentoActionPerformed

    private void cbxBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxBancoActionPerformed
        if(cbxBanco.getSelectedIndex()!=0){
            codBanco=buscaCodBanco((String) cbxBanco.getSelectedItem());
            banco=daoBanco.consultar(codBanco);
            ArrayList<Agencia> agencias = daoAgencia.listarAgencia(codBanco);
        
            for(int x=0;x<agencias.size();x++){
                cbxAgencia.addItem(String.valueOf(agencias.get(x).getNumAgencia()));
            }
        }
        
    }//GEN-LAST:event_cbxBancoActionPerformed

    private void cbxAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxAgenciaActionPerformed
        if(cbxAgencia.getSelectedIndex()!=0){
             numAgencia=Integer.parseInt((String) cbxAgencia.getSelectedItem());
             agencia=daoAgencia.consultar(codBanco, numAgencia);
             ArrayList<ContaBancaria> contasB = daoContaBancaria.listarContaBancaria(codBanco,numAgencia);
             if(contasB.size()!=0){
                  for(int x=0;x<contasB.size();x++){
                    cbxContaBancaria.addItem(String.valueOf(contasB.get(x).getNumConta()));
                  }
             }
        } 
    }//GEN-LAST:event_cbxAgenciaActionPerformed

    private void cbxContaBancariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxContaBancariaActionPerformed
          if(cbxContaBancaria.getSelectedIndex()!=0){
                contab=Integer.parseInt((String) cbxContaBancaria.getSelectedItem());
                contaBancaria=daoContaBancaria.consultar(codBanco, numAgencia, contab);
                System.out.println(contaBancaria.getCodBanco());
                 System.out.println(contaBancaria.getNumAgencia());
                  System.out.println(contaBancaria.getNumConta());
                if(contaBancaria.getSaldo()>=0){
                    //jtxtSaldo.setBackground(new ColorUIResource(204,255,204));
                     jtxtSaldo.setBackground(new Color(204, 255, 204));
                }
                else{
                    jtxtSaldo.setBackground(new Color(255,204,204));
                }
            
        
                
                jtxtSaldo.setText(String.valueOf(contaBancaria.getSaldo()));
          }
    }//GEN-LAST:event_cbxContaBancariaActionPerformed

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
            Object[]options = { "Sim","Cancelar"};
            Icon figura = new ImageIcon (getToolkit().createImage(getClass().getResource("/fatec/tg/icon/cash.png")));
        if(cbxTipoPagamento.getSelectedItem().equals("Selecione")){
            JOptionPane.showMessageDialog(this, "Selecione a forma de pagamento desejada.");
        }  
        else if(cbxTipoPagamento.getSelectedItem().equals("Dinheiro")){
            completaTitulo();
             tituloParcela.setStatusPag("P");
            if(JOptionPane.showOptionDialog(null, "Você confirma o Pagamento deste Título? ", "Aviso de Pagamento",
            JOptionPane.DEFAULT_OPTION,JOptionPane.WARNING_MESSAGE, 
            figura, options, options[0])==0){
                 daoTituloParcela.PagarDinheiro(tituloParcela);
                 gerenteJanelas.abrirJanelas(GuiContasAPagar.getInstancia());
                 dispose();
               
                conexao.fecharConexao();
            }
        }
        else if(cbxTipoPagamento.getSelectedItem().equals("Transferencia Bancaria")){
            
            if(cbxAgencia.getSelectedIndex()==0 ||cbxBanco.getSelectedIndex()==0 || cbxContaBancaria.getSelectedIndex()==0){
                JOptionPane.showMessageDialog(this, "Banco, Agencia e Conta Bancaria são campos obrigatorios!");
            }else{
                 completaTitulo();
                 tituloParcela.setStatusPag("P");
                  tituloParcela.setTransfBanc(String.valueOf("Banco: "+ buscaNomeBanco(codBanco)+" Agencia: "+numAgencia+" Conta: "+contab));
                  if(JOptionPane.showOptionDialog(null, "Voce confirma o Pagamento deste Título? ", "Aviso de Pagamento",
                    JOptionPane.DEFAULT_OPTION,JOptionPane.WARNING_MESSAGE, 
                    figura, options, options[0])==0){
                    daoTituloParcela.PagarTransBanc(tituloParcela);
                    dispose();
                    gerenteJanelas.abrirJanelas(GuiContasAPagar.getInstancia());
                    conexao.fecharConexao();
                  }
            }
           
        }
            else if(cbxTipoPagamento.getSelectedItem().equals("Cheque")){
            
            if(jtxtDtPredatado.getText().replace("/","").replace(" ","").length()<8 ||txtNumCheque.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Prédatado e N° do Cheque são campos obrigatorios!");
            }else{
                 completaTitulo();
                 tituloParcela.setStatusPag("P");
                  tituloParcela.setNumCheque(txtNumCheque.getText());
                  tituloParcela.setChequePara(jtxtDtPredatado.getText());
                  if(JOptionPane.showOptionDialog(null, "Voce confirma o Pagamento deste Título? ", "Aviso de Pagamento",
                    JOptionPane.DEFAULT_OPTION,JOptionPane.WARNING_MESSAGE, 
                    figura, options, options[0])==0){
                    daoTituloParcela.PagarCheque(tituloParcela);
                    dispose();
                    gerenteJanelas.abrirJanelas(GuiContasAPagar.getInstancia());
                    conexao.fecharConexao();
                  }
            }
           
        }
        else if(cbxTipoPagamento.getSelectedItem().equals("Remessa")){
            
           if(cbxAgencia.getSelectedIndex()==0 ||cbxBanco.getSelectedIndex()==0 || cbxContaBancaria.getSelectedIndex()==0){
                JOptionPane.showMessageDialog(this, "Banco, Agencia e Conta Bancaria são campos obrigatorios!");
            }else{
                 completaTitulo();
                  tituloParcela.setStatusPag("A");
                   LocalDate hoje = LocalDate.now();
                   DateTimeFormatter f = DateTimeFormatter.ofPattern("dd/MM/yyyy");
                   arquivoRemessa= new DaoArquivoRemessa(conexao.conectar()).consultarHj(codBanco, numAgencia, contab,hoje.format(f));
                     if(arquivoRemessa==null){
                          System.out.println("banco ta zero");
                          arquivoRemessa=new ArquivoRemessa(daoArquivoRemessa.obterCodArqRem()+1);
                          arquivoRemessa.setDataRemessa(hoje.format(f));
                          arquivoRemessa.setStatus("A");
                          arquivoRemessa.setBanco(banco);
                          arquivoRemessa.setAgencia(agencia);
                          arquivoRemessa.setContaBancaria(contaBancaria);
                          
                      }
                  if(JOptionPane.showOptionDialog(null, "Voce confirma a inclusao deste Título na Remessa: "+ arquivoRemessa.getCodigo()+" ? ", "Aviso de Pagamento",
                    JOptionPane.DEFAULT_OPTION,JOptionPane.WARNING_MESSAGE, 
                    figura, options, options[0])==0){
                     
                     if(daoArquivoRemessa.consultarHj(codBanco, numAgencia, contab, hoje.format(f))==null)
                      daoArquivoRemessa.inserir(arquivoRemessa);
                      
                      remessaTitulo=new RemessaTitulo(arquivoRemessa, tituloParcela);
                      
                      daoTituloParcela.PagarRemessa(tituloParcela);
                      daoRemessaTitulo.inserir(remessaTitulo);
                       dispose();
                       gerenteJanelas.abrirJanelas(GuiContasAPagar.getInstancia());
                       conexao.fecharConexao();
                  }
            }
           
        }
        else{
            completaTitulo();
             tituloParcela.setStatusPag("P");
            if(JOptionPane.showOptionDialog(null, "Você confirma o Pagamento deste Título? ", "Aviso de Pagamento",
            JOptionPane.DEFAULT_OPTION,JOptionPane.WARNING_MESSAGE, 
            figura, options, options[0])==0){
                 daoTituloParcela.PagarDinheiro(tituloParcela);
                 gerenteJanelas.abrirJanelas(GuiContasAPagar.getInstancia());
                 dispose();
               
                conexao.fecharConexao();
            }
        }
        
        
        
        
    }//GEN-LAST:event_btnPagarActionPerformed

    private void jtxtValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtValorActionPerformed

    private void jtxtDtPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDtPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDtPagamentoActionPerformed

     /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiPagarTitulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiPagarTitulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiPagarTitulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiPagarTitulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiPagarTitulo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnPagar;
    private javax.swing.JComboBox<String> cbxAgencia;
    private javax.swing.JComboBox<String> cbxBanco;
    private javax.swing.JComboBox<String> cbxContaBancaria;
    private javax.swing.JComboBox<String> cbxTipoPagamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelBancario;
    private javax.swing.JPanel jPanelCheque;
    private javax.swing.JFormattedTextField jtxtDtPagamento;
    private javax.swing.JFormattedTextField jtxtDtPredatado;
    private javax.swing.JFormattedTextField jtxtDtVencimento;
    private javax.swing.JFormattedTextField jtxtJuros;
    private javax.swing.JFormattedTextField jtxtMulta;
    private javax.swing.JFormattedTextField jtxtSaldo;
    private javax.swing.JFormattedTextField jtxtValPagar;
    private javax.swing.JFormattedTextField jtxtValor;
    private javax.swing.JTextField txtCodBarras;
    private javax.swing.JTextField txtFornecedor;
    private javax.swing.JTextField txtHistorico;
    private javax.swing.JTextField txtNumCheque;
    private javax.swing.JTextField txtNumLancamento;
    private javax.swing.JTextField txtNumParcelas;
    private javax.swing.JTextField txtTitularidade;
    // End of variables declaration//GEN-END:variables
     private Conexao conexao=null;
    private Titulo titulo=null;
    private TituloParcela tituloParcela=null;
    private FornecFisica fornecFisica =null;
    private FornecJuridica fornecJuridica=null;
    private DaoFornecPF daoFornecPF=null;
    private DaoFornecPJ daoFornecPJ=null;
    private DaoFornecedor daoFornecedor=null;
    private Fornecedor fornecedor=null;
    private DaoTitulo daoTitulo=null;
    private DaoTituloParcela daoTituloParcela=null;
    private DaoBanco daoBanco=null;
    private DaoAgencia daoAgencia=null;
    private Agencia agencia=null;
    private DaoContaBancaria daoContaBancaria=null;
    private ContaBancaria contaBancaria=null;
    private Banco banco=null;
    private int numLanc=0;
    private int numParc=0;
    private int codBanco=0;
    private int numAgencia=0;
    private int contab=0;
    private TipoPagamento tipoPagamento=null;
    private DaoTpPagamento daotpPagamento=null;
    private DaoArquivoRemessa daoArquivoRemessa=null;
    private ArquivoRemessa arquivoRemessa=null;
    private RemessaTitulo remessaTitulo=null;
    private DaoRemessaTitulo daoRemessaTitulo=null;

}
